apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: keycloak-datastore
  name: keycloak-datastore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
