apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/kong-net: "true"
    io.kompose.service: kong-migrations-up
  name: kong-migrations-up
spec:
  containers:
    - args:
        - kong
        - migrations
        - up
        - '&&'
        - kong
        - migrations
        - finish
      env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_DATABASE
          value: kong
        - name: KONG_PG_HOST
          value: 10.88.2.26
        - name: KONG_PG_PASSWORD
          value: kong
        - name: KONG_PG_USER
          value: kong
      image: kong:2.3.2-alpine
      name: kong-migrations-up
      resources: {}
  restartPolicy: OnFailure
status: {}
